### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by twidul** [juzt3/CRTPi-HDMI2YPbPr#2]
Hello! first of all thank you for your project.

I am running into an issue, when pasting the command prompt line i get the following message : "The system cannot find the file specified"

Could you direct me please in what I am doing wrong?

Raspberry is conected to wifi, SSH is enabled.

Thank you

![eroare retropie](https://github.com/juzt3/CRTPi-HDMI2YPbPr/assets/158744154/1b8c8a08-7035-45d6-91f4-a75fb787b499)

**Comment by juzt3** [comment]
Hi, you can also connect your raspberry to a hdmi monitor and type curl -s https://raw.githubusercontent.com/juzt3/CRTPi-HDMI2YPbPr/main/setup.sh directly there
